### ISSUE TITLE
Header and nav 

### ISSUE THREAD

**Issue by RandSohail** [GSG-G11/tecStorm-portfolio#6]
### Tasks

- [ ]  Add logo and title in the left side of the navbar
- [ ]  Add links list at the right side of the navbar
- [ ]  make links work smoothly 
- [ ]  Add and style the team's bio 

#### Screenshot
![Screenshot from 2022-01-25 18-29-30](https://user-images.githubusercontent.com/76879976/151018094-e7b63fec-a5b6-4dd4-ab86-618ea125e925.png)
